name: Build
on:
  repository_dispatch:
    types: [release]
jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
