name: Build
on:
  repository_dispatch:
    types: [release]
  push:
    tags:
      - '*'
jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - run: Compress-Archive -Path target/release/*.exe -DestinationPath pylaunch.zip
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "pylaunch.zip"
          token: ${{ secrets.GITHUB_TOKEN }}